//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub agent_id: String,
    pub display_name: String,
    pub image: String,
    pub entrypoint: Option<String>,
    #[sea_orm(column_type = "Json")]
    pub env_vars: Json,
    #[sea_orm(column_type = "Json")]
    pub livekit_permissions: Json,
    pub default_room_behavior: String,
    pub auto_restart_policy: String,
    #[sea_orm(column_type = "Json")]
    pub resource_limits: Json,
    pub is_enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_instances::Entity")]
    AgentInstances,
    #[sea_orm(has_many = "super::agent_logs::Entity")]
    AgentLogs,
    #[sea_orm(has_many = "super::agent_metrics::Entity")]
    AgentMetrics,
    #[sea_orm(has_many = "super::agent_rooms::Entity")]
    AgentRooms,
}

impl Related<super::agent_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentInstances.def()
    }
}

impl Related<super::agent_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentLogs.def()
    }
}

impl Related<super::agent_metrics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentMetrics.def()
    }
}

impl Related<super::agent_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentRooms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}