//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::users::Entity as Users;
pub use super::api_keys::Entity as ApiKeys;
pub use super::rooms::Entity as Rooms;
pub use super::ingress::Entity as Ingress;
pub use super::egress::Entity as Egress;
pub use super::sip::Entity as Sip;
pub use super::configs::Entity as Configs;
pub use super::metrics::Entity as Metrics;
pub use super::agents::Entity as Agents;
pub use super::agent_instances::Entity as AgentInstances;
pub use super::agent_logs::Entity as AgentLogs;
pub use super::agent_metrics::Entity as AgentMetrics;
pub use super::agent_rooms::Entity as AgentRooms;
