//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::users::Entity as Users;
pub use super::api_keys::Entity as ApiKeys;
pub use super::rooms::Entity as Rooms;
pub use super::ingress::Entity as Ingress;
pub use super::egress::Entity as Egress;
pub use super::sip::Entity as Sip;
pub use super::configs::Entity as Configs;
pub use super::metrics::Entity as Metrics;
pub use super::agents::Entity as Agents;
pub use super::agent_instances::Entity as AgentInstances;
pub use super::agent_logs::Entity as AgentLogs;
pub use super::agent_metrics::Entity as AgentMetrics;
pub use super::agent_rooms::Entity as AgentRooms;

pub use super::projects::Entity as Projects;
pub use super::project_ai_configs::Entity as ProjectAIConfigs;
pub use super::sessions::Entity as Sessions;
pub use super::analytics_snapshots::Entity as AnalyticsSnapshots;
pub use super::sip_trunks::Entity as SipTrunks;
pub use super::dispatch_rules::Entity as DispatchRules;
pub use super::room_templates::Entity as RoomTemplates;
pub use super::layout_templates::Entity as LayoutTemplates;
pub use super::auto_recording_rules::Entity as AutoRecordingRules;
pub use super::service_accounts::Entity as ServiceAccounts;
pub use super::storage_configs::Entity as StorageConfigs;
pub use super::regions::Entity as Regions;
pub use super::roles::Entity as Roles;
pub use super::audit_logs::Entity as AuditLogs;
pub use super::transcripts::Entity as Transcripts;
